### ISSUE TITLE
Steam Category

### ISSUE THREAD

**Issue by HopeTrash** [RobertMillett/Curator#11]
Is the program able to put the games in a steam category?

**Comment by RobertMillett** [comment]
Yes, the name of the Console the games are added under becomes the Steam Category. Would you like the ability to further categorise the games?

**Comment by HopeTrash** [comment]
Yeah it would be nice if i could put it in a serie category + a console category

**Comment by RobertMillett** [comment]
This would only make sense when applying a category to multiple ROMs at once. If you're applying categories to ROMs one at a time, you can just do that inside Steam. If you're doing it to multiple games at once, that is fair, but I would need to create a dialog for managing additional categories and I'm a little concerned about cluttering the UI at this point.
